import "./globals.css";
import SideBar from '@/app/components/SideBar'
import ReduxProvider from "./redux/ReduxProvider";
import { Toaster } from 'react-hot-toast';


// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-gray-50 ">
        <ReduxProvider>
          <div className="flex">
            
            {/* Sidebar */}
            <aside className="w-64 shrink-0">
              <SideBar />
            </aside>

            {/* Main content */}
            <main className="flex-1 flex justify-center px-2 sm:px-2">
              <div className="w-full max-w-7xl">
                {children}
                <Toaster position="top-right" reverseOrder={false} />
              </div>
            </main>

          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}

