import "./globals.css";
import SideBar from '@/app/components/SideBar'
import ReduxProvider from "./redux/ReduxProvider";
import { Toaster } from 'react-hot-toast';


// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex">
        <ReduxProvider>
          
            <SideBar />
            <main >
              {children}
              <Toaster position="top-right" reverseOrder={false} />
            </main>
         
        </ReduxProvider>       
      </body>
    </html>
  );
}
